services:

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ports:
      - 1865:80
      - 5678:5678
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - ./data:/app/cat/data
  
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: '${MEILISEARCH_MASTER_KEY}'
      MEILI_EXPERIMENTAL_VECTOR_STORE: 'true'
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped
  
  #telegram_bot:
  #  build:
  #    context: .
  #    dockerfile: ./tele_gram/Dockerfile
  #  container_name: telegram_bot_main
  #  working_dir: /app
  #  environment:
  #    - BOT_TOKEN=${BOT_TOKEN}
  #  command: ["python", "-m", "tele_gram.main"]
  #  restart: unless-stopped
